# Info
info:
  component: Invoice Service

spring:
  application:
    name: invoice-service
    instance: dev

server:
  port: 8081
  servlet:
    context-path: /api/invoice-service
  forward-headers-strategy: framework

